sonar.projectKey=citizen-grievance-portal
sonar.projectName=citizen-grievance-portal
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=sqp_7b2b97dd86a967a634242d764b4f04597dff2d2f

# Only analyze source folders
sonar.sources=citizen-grievance-backend/src,citizen-grievance-frontend/src

# Java compiled classes
sonar.java.binaries=citizen-grievance-backend/target/classes

sonar.sourceEncoding=UTF-8

sonar.exclusions=\
**/node_modules/**,\
**/target/**,\
**/dist/**,\
**/build/**,\
**/.git/**,\
**/.idea/**,\
**/.vscode/**,\
**/coverage/**,\
**/*.min.js,\
**/*.bundle.js,\
**/*.log,\
**/.env,\
**/.env.*